# Generated by Django 3.1 on 2020-08-20 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_name', models.CharField(max_length=200)),
                ('event_category', models.CharField(choices=[('CONFERENCE', 'Conference'), ('SEMINAR', 'Seminar'), ('CONGRESS', 'Congress'), ('COURSE', 'Course')], max_length=15)),
                ('event_place', models.CharField(max_length=200)),
                ('event_address', models.CharField(max_length=200)),
                ('event_initial_date', models.DateTimeField()),
                ('event_final_date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PRESENCIAL', 'Presencial')], max_length=15)),
                ('thumbnail', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
